<a href="https://colab.research.google.com/github/axshay007/Numpy_tutorial/blob/main/01_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![image.png](attachment:image.png)

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np #np is how we will call numpy going forward

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array([1,2])

array([1, 2])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(11,35)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34])

In [7]:
np.arange(10,50,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

### zeros and ones

Generate arrays of zeros or ones

In [8]:
np.zeros(3, dtype='int8')

array([0, 0, 0], dtype=int8)

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(10,20,3) # throee evenly spaced between 0 and 10.

array([10., 15., 20.])

In [13]:
np.linspace(0,10,50) 
#fifty evenly spaced out numbers between 0 and 10. One dimensinal vector identified by only 1 set of brackets in front of the array.

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [14]:
np.eye(4) #4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [15]:
np.random.rand(2) # 0 to 1

array([0.46722979, 0.44756591])

In [16]:
np.random.rand(5,5) #5x5

array([[0.0245371 , 0.3874358 , 0.5855601 , 0.01539375, 0.13686742],
       [0.25394846, 0.0676843 , 0.4670732 , 0.39112353, 0.02400311],
       [0.86188624, 0.13047384, 0.15840502, 0.64075077, 0.19056137],
       [0.96132997, 0.27751239, 0.58280721, 0.91829415, 0.50071133],
       [0.50329899, 0.72770062, 0.93143922, 0.32685898, 0.44025837]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(8) #around 0 

array([ 0.25555106,  1.66055719, -1.87538266, -0.61281925, -0.74117021,
        1.81277495,  0.8511989 , -0.47666369])

In [18]:
np.random.randn(5,5) #5x5 around 0

array([[ 0.69429631, -0.48384932, -0.94117199,  1.10263535,  1.47158437],
       [ 0.00622195, -0.29773743,  0.45869598,  0.72474914,  0.55178454],
       [ 1.14181936, -1.93145843,  1.05986951, -0.67539566, -0.80242255],
       [-0.76954321, -0.72543782,  1.67663153,  1.48196349,  0.00888169],
       [ 1.03940987,  0.40302411, -1.89563366,  0.11878663,  0.804321  ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
np.random.randint(1,100) #1 random number between 1 up to but not inlcuding the higher number given.

40

In [20]:
np.random.randint(1,100,10) #10 random numbers between 1 up to but not inlcuding the higher number given.

array([12, 28, 87,  1,  9, 47, 23, 78, 37, 81])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [21]:
arr = np.arange(25) #ordered, from 0 to 24, 1D array.
ranarr = np.random.randint(0,50,10) #10 random numbers between 0 up to but not including 50

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([26, 25, 42, 24,  1, 22, 33, 49, 35, 12])

## Reshape
Returns an array containing the same data with a new shape.

In [24]:
arr.reshape(5,5) #same data, but reshaped into a 5x5 (2D) structure.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [25]:
ranarr #recheck what we had in it

array([26, 25, 42, 24,  1, 22, 33, 49, 35, 12])

In [26]:
ranarr.max() #what is the MAX value

49

In [27]:
ranarr.argmax() #at what index value is the MAX value located.

7

In [28]:
ranarr.min() #what is the MIN value

1

In [29]:
ranarr.argmin() #at what index value is the MIN value located.

4

## Shape

Shape is an attribute that arrays have (not a method):

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
# Vector
arr.shape # (25,) means "arr" is 1 dimensinal

(25,)

In [32]:
#reshape to 2D, 1 row, 25 columns
arr.reshape(1,25)  # Notice the two sets of brackets in the output

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25).shape # shape (1,25) confirms arr is now 2D, 1 row, 25 columns.

(1, 25)

In [34]:
#reshape still in 2D, but 25 rows, 1 column
arr.reshape(25,1)  # Still notice the two sets of brackets in the output

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25,1).shape # shape (25,1) confirms arr is still 2D, but now with 25 rows, and only 1 column.

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [36]:
# arr.dtype

In [37]:
# to save yourself typing you can import numpy functions
from numpy.random import randint

In [38]:
randint(2,10) #get a random integer between [2, 10) - including 2, up to but NOT including 10.

8

# Great Job!